In [1]:
import torch
import numpy as np

### Creating Tensor in PyTorch

A scalar is a single independent value, a 1D array of values is called a vector, a 2D array of values is called a matrix, and any array of values that is more than 2D is simply called a tensor.



In [2]:
# Creating Tensors with ones

torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [3]:
# To create a tensor with dtype : int

torch.ones((2,3), dtype= torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [4]:
# Creating Tensor with integer zeros

torch.zeros((2,3), dtype= torch.int16)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)

In [5]:
# Creating tensor with specific value

torch.full((2,2), 3.5)

tensor([[3.5000, 3.5000],
        [3.5000, 3.5000]])

In [6]:
# Creating an empty tensor

torch.empty((3,3))

tensor([[8.5737e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])

In [7]:
# Creating a tensor from uniform distribution : [0,1]

torch.rand((2,2))

tensor([[0.6092, 0.8598],
        [0.5550, 0.3786]])

In [8]:
# Creating tensor with standard normal distribution (mean:0, variance:1)

torch.randn((2,2))

tensor([[ 2.8530,  0.2535],
        [-1.2039, -0.3790]])

In [9]:
# Using Integer values : lower and upper limit

torch.randint(low = 10, high = 20, size = (2,2))

tensor([[12, 11],
        [14, 10]])

In [10]:
# Creating Tensor from existing data

x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
print('The datatype of tensor: ', x.dtype)
print('Size of Tensor:', x.shape)


The datatype of tensor:  torch.int64
Size of Tensor: torch.Size([2, 3])


In [12]:
# Lets create a tensor, y which has similar attributes to x

y = torch.ones_like(x)
y

tensor([[1, 1, 1],
        [1, 1, 1]])

### Exploring the NumPy Bridge

In [13]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Converting it to PyTorch Tensor

b = torch.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
b.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

### Exploring Gradients

In [16]:
# Unlike tensors made so far, we will add a key, to tell PyTorch it needs to perform gradient differentiation

x = torch.full((2,3), 4, requires_grad= True)
x

/pytorch/aten/src/ATen/native/TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [17]:
# defining slightly more complex function

y = (2 * x**2) + 3 
y

tensor([[35., 35., 35.],
        [35., 35., 35.]], grad_fn=<AddBackward0>)

In [18]:
y.backward(torch.ones_like(x))

In [19]:
x.grad

tensor([[16., 16., 16.],
        [16., 16., 16.]])

In [20]:
# Turning off the gradient requirement

x.requires_grad

True

In [21]:
x.requires_grad_(False)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

### Viewing Tensors in PyTorch

While working with tensors and dealing with neural networks, we often need to go through and rearrange data in the tensors so that the dimensions of the tensors fit the needs of the architecture

In [22]:
x = torch.Tensor([1,2,3,4])
print(x)
print(torch.reshape(x, (2,2)))

# Looking into resize method:
y = torch.Tensor([1,2,3,4,5,6])
print(y.shape)
y.resize_((2,2))

tensor([1., 2., 3., 4.])
tensor([[1., 2.],
        [3., 4.]])
torch.Size([6])


tensor([[1., 2.],
        [3., 4.]])

With the view() method, you can choose not to mention one of the dimensions and arrange the rest of them, and PyTorch will calculate the missing dimension 

In [23]:
# most common method is .view()

a = torch.Tensor([1,2,3,4,5,6])

a.view((3,-1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

You can use the dimension of another tensor and make a given tensor resemble the dimension of that tensor without affecting the actual dimensions of either of them.

In [24]:
a = torch.Tensor([[1,2,3],[4,5,6]])
print(a.shape)

b = torch.Tensor([1,2,3,4,5,6])
print(b.shape)

b.view_as(a)

torch.Size([2, 3])
torch.Size([6])


tensor([[1., 2., 3.],
        [4., 5., 6.]])