In [10]:
import torch
import torch.nn as nn

In [11]:
# Exploring Convolution Operation

nn.Conv2d(3,kernel_size=3, out_channels= 16, stride= 2 , padding= 1)

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

In [12]:
# Exploring the Pooling Layers

max_pool = nn.MaxPool2d(kernel_size= 3 , stride= 1)

a = torch.FloatTensor(3,5,5).random_(0,10)
print(a)
#print(a.shape)

print(max_pool(a))

avg_pool = nn.AvgPool2d(kernel_size= 3, stride= 1)

print(avg_pool(a))

tensor([[[5., 9., 8., 4., 6.],
         [1., 6., 2., 3., 3.],
         [3., 3., 1., 2., 2.],
         [9., 2., 0., 5., 0.],
         [8., 5., 8., 3., 0.]],

        [[6., 6., 5., 5., 9.],
         [2., 4., 0., 2., 8.],
         [1., 7., 7., 3., 3.],
         [8., 7., 2., 1., 1.],
         [1., 1., 0., 6., 2.]],

        [[1., 4., 3., 3., 5.],
         [1., 0., 2., 2., 8.],
         [3., 5., 5., 1., 1.],
         [6., 6., 9., 7., 0.],
         [6., 1., 1., 9., 2.]]])
tensor([[[9., 9., 8.],
         [9., 6., 5.],
         [9., 8., 8.]],

        [[7., 7., 9.],
         [8., 7., 8.],
         [8., 7., 7.]],

        [[5., 5., 8.],
         [9., 9., 9.],
         [9., 9., 9.]]])
tensor([[[4.2222, 4.2222, 3.4444],
         [3.0000, 2.6667, 2.0000],
         [4.3333, 3.2222, 2.3333]],

        [[4.2222, 4.3333, 4.6667],
         [4.2222, 3.6667, 3.0000],
         [3.7778, 3.7778, 2.7778]],

        [[2.6667, 2.7778, 3.3333],
         [4.1111, 4.1111, 3.8889],
         [4.6667, 4.8889, 3.8889

PyTorch cannot process an image pixel directly and needs to have the contents as tensors. To get around this, **torchvision**, being a specialized library for vision and image-related tasks, provides a module called transform, which provides APIs for converting pixels into tensors, normalizing standard scaling, and so on

In [20]:
from torchvision import transforms

# Creating a Tensor From Image

print(transforms.ToTensor())

# Normalize the Image Tensor

print(transforms.Normalize(0.5,0.5))

# To resize an image, we use following method

print(transforms.Resize((10,10)))

# Transform to Crop the Image

print(transforms.CenterCrop(10))

# Transformations to Pad the image tensors

print(transforms.Pad(1,0))

ToTensor()
Normalize(mean=0.5, std=0.5)
Resize(size=(10, 10), interpolation=PIL.Image.BILINEAR)
CenterCrop(size=(10, 10))
Pad(padding=1, fill=0, padding_mode=constant)


In [21]:
# To chain multiple transformations

transforms.Compose([
                    transforms.CenterCrop(10),
                    transforms.ToTensor()
])

Compose(
    CenterCrop(size=(10, 10))
    ToTensor()
)

Data augmentation is an important technique in deep learning and computer vision. For any model dealing with deep learning or computer vision, the amount of data available is crucial to see how well the model performs

In [25]:
# Cropping a Section of Image Randomly

print(transforms.RandomCrop(10))

# Randomly Flipping the image Horizontally & Vertically

print(transforms.RandomHorizontalFlip(p = 0.3))
print(transforms.RandomVerticalFlip(p=0.2))

# Adding Brightness,Saturation,Contrast

print(transforms.ColorJitter(brightness= 0.2, contrast= 0.4, saturation= 0.3, hue= 0.2))

RandomCrop(size=(10, 10), padding=None)
RandomHorizontalFlip(p=0.3)
RandomVerticalFlip(p=0.2)
ColorJitter(brightness=[0.8, 1.2], contrast=[0.6, 1.4], saturation=[0.7, 1.3], hue=[-0.2, 0.2])
